/**
 * NFL 日本人ブログ・メディア一覧データマスタ (提出用シート準拠)
 */

export type NFLTeamCode =
  | "ARI" | "ATL" | "BAL" | "BUF" | "CAR" | "CHI" | "CIN" | "CLE"
  | "DAL" | "DEN" | "DET" | "GB"  | "HOU" | "IND" | "JAX" | "KC"
  | "LV"  | "LAC" | "LAR" | "MIA" | "MIN" | "NE"  | "NO"  | "NYG"
  | "NYJ" | "PHI" | "PIT" | "SF"  | "SEA" | "TB"  | "TEN" | "WAS";

export interface BlogFilterRule {
  /** タイトルにこのいずれかが含まれている必要がある場合 */
  titleKeywords?: string[];
  /** カテゴリーやタグ、URLに含まれるべき文字列 */
  categoryOrTagKeywords?: string[];
  /** 特定のURLパターンのもののみ取得する場合 */
  targetUrlPattern?: RegExp;
}

export interface NFLMediaLinkItem {
  id: number;
  name: string;
  url: string;
  category: "team_blog" | "general" | "general_and_team" | "special";
  targetTeam?: NFLTeamCode;
  targetTeamName?: string;
  statusText: string;
  /** 許諾済みフラグ (許諾済 / 済) */
  isPermitted: boolean;
  /** 最上位固定フラグ (No.45 Ames) */
  isPinnedTop?: boolean;
  /** チームページの Latest News に掲載するか (No.1〜15) */
  showInTeamLatest: boolean;
  /** 記事ピックアップ用個別ルール */
  filterRule?: BlogFilterRule;
  /** 予想されるRSSフィードURL */
  rssUrl?: string;
  memo?: string;
}

export const NFL_MEDIA_LINKS: NFLMediaLinkItem[] = [
  {
    id: 1,
    name: "たーくん",
    url: "https://note.com/taakun07",
    category: "team_blog",
    targetTeam: "GB",
    targetTeamName: "Green Bay Packers",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    rssUrl: "https://note.com/taakun07/rss",
    memo: "全てOK",
  },
  {
    id: 2,
    name: "にわかダラスカウボーイズファン・ツミキ",
    url: "https://note.com/huge_puma7884",
    category: "team_blog",
    targetTeam: "DAL",
    targetTeamName: "Dallas Cowboys",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    rssUrl: "https://note.com/huge_puma7884/rss",
    memo: "全てOK",
  },
  {
    id: 3,
    name: "びるずだいなすてぃ",
    url: "https://note.com/billsdynasty",
    category: "team_blog",
    targetTeam: "BUF",
    targetTeamName: "Buffalo Bills",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    rssUrl: "https://note.com/billsdynasty/rss",
    memo: "全てOK",
  },
  {
    id: 4,
    name: "ふぅだっと。 （NFL / セインツ）",
    url: "https://ameblo.jp/yoda-da-yon",
    category: "team_blog",
    targetTeam: "NO",
    targetTeamName: "New Orleans Saints",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    rssUrl: "https://rssblog.ameba.jp/yoda-da-yon/rss20.xml",
    memo: "全てOK",
  },
  {
    id: 5,
    name: "鶴嘴温助",
    url: "https://note.com/gentle_dahlia649",
    category: "team_blog",
    targetTeam: "DET",
    targetTeamName: "Detroit Lions",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    rssUrl: "https://note.com/gentle_dahlia649/rss",
    memo: "全てOK",
  },
  {
    id: 6,
    name: "ノーハドル書きなぐる - Patriots Fan Blog -",
    url: "https://foxboro.blog.fc2.com/",
    category: "team_blog",
    targetTeam: "NE",
    targetTeamName: "New England Patriots",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    rssUrl: "https://foxboro.blog.fc2.com/?xml",
    memo: "全てOK",
  },
  {
    id: 7,
    name: "Jaguars Note",
    url: "https://www.jaguars-note.com/",
    category: "team_blog",
    targetTeam: "JAX",
    targetTeamName: "Jacksonville Jaguars",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    rssUrl: "https://www.jaguars-note.com/feed/",
    memo: "全てOK",
  },
  {
    id: 8,
    name: "村田",
    url: "https://note.com/murata_north",
    category: "team_blog",
    targetTeam: "NYG",
    targetTeamName: "New York Giants",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    rssUrl: "https://note.com/murata_north/rss",
    memo: "全てOK",
  },
  {
    id: 9,
    name: "GO! HAWKS!",
    url: "https://seahawks12s.blog.jp/",
    category: "team_blog",
    targetTeam: "SEA",
    targetTeamName: "Seattle Seahawks",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    rssUrl: "https://seahawks12s.blog.jp/index.rdf",
    memo: "全てOK",
  },
  {
    id: 10,
    name: "リトルナイナー",
    url: "https://note.com/atsu_49ers",
    category: "team_blog",
    targetTeam: "SF",
    targetTeamName: "San Francisco 49ers",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    filterRule: {
      titleKeywords: ["49ers", "フォーティナイナーズ", "ナイナーズ"],
    },
    rssUrl: "https://note.com/atsu_49ers/rss",
    memo: "【49ers】によるタイトルでのタグ仕訳必要",
  },
  {
    id: 11,
    name: "Yukirhythm-ユーキリズム-",
    url: "https://ameblo.jp/yukirhythm5/",
    category: "team_blog",
    targetTeam: "PHI",
    targetTeamName: "Philadelphia Eagles",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    filterRule: {
      categoryOrTagKeywords: ["イーグルス", "Eagles", "theme-10093848591"],
      targetUrlPattern: /theme-10093848591/,
    },
    rssUrl: "https://rssblog.ameba.jp/yukirhythm5/rss20.xml",
    memo: "カテゴリー（https://ameblo.jp/yukirhythm5/theme-10093848591.html）のみ",
  },
  {
    id: 12,
    name: "茶犬 NFLブログ",
    url: "https://nflchao.com/",
    category: "general_and_team",
    targetTeam: "CLE",
    targetTeamName: "Cleveland Browns",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    filterRule: {
      categoryOrTagKeywords: ["ブラウンズ", "Browns", "cat_36746"],
      targetUrlPattern: /cat_36746/,
    },
    rssUrl: "https://nflchao.com/feed/",
    memo: "ブラウンズタグのみチームページへ",
  },
  {
    id: 13,
    name: "K猫のDENファン日記",
    url: "https://www.kcatfootball.net/",
    category: "team_blog",
    targetTeam: "DEN",
    targetTeamName: "Denver Broncos",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    filterRule: {
      categoryOrTagKeywords: ["デンバーブロンコス", "ブロンコス", "Broncos", "cat_401706"],
      targetUrlPattern: /cat_401706/,
    },
    rssUrl: "https://www.kcatfootball.net/index.rdf",
    memo: "デンバーブロンコスタグのみチームページへ",
  },
  {
    id: 14,
    name: "JETS狂の宴",
    url: "https://jets94.com/",
    category: "team_blog",
    targetTeam: "NYJ",
    targetTeamName: "New York Jets",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    filterRule: {
      categoryOrTagKeywords: ["ジェッツ", "Jets"],
    },
    rssUrl: "https://jets94.com/feed/",
    memo: "ジェッツタグのみチームページへ",
  },
  {
    id: 15,
    name: "アメフトーーク",
    url: "https://note.com/amefootalk",
    category: "general_and_team",
    targetTeam: "DEN",
    targetTeamName: "Denver Broncos",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: true,
    filterRule: {
      titleKeywords: ["ブロンコス", "Broncos"],
    },
    rssUrl: "https://note.com/amefootalk/rss",
    memo: "タイトルにブロンコスがあるものはチームページへ",
  },
  {
    id: 16,
    name: "sleepy（アメフトニウム）",
    url: "https://note.com/sleepy_nfl_fan",
    category: "general",
    statusText: "許諾済",
    isPermitted: true,
    showInTeamLatest: false,
    rssUrl: "https://note.com/sleepy_nfl_fan/rss",
  },
  {
    id: 17,
    name: "Crazy Dol-Fan Diary",
    url: "https://ameblo.jp/shulasarmytokyo/",
    category: "team_blog",
    targetTeam: "MIA",
    targetTeamName: "Miami Dolphins",
    statusText: "済",
    isPermitted: true,
    showInTeamLatest: false,
    rssUrl: "https://rssblog.ameba.jp/shulasarmytokyo/rss20.xml",
    memo: "全てOK",
  },
  {
    id: 18,
    name: "P-BLUE",
    url: "https://note.com/pantherblue",
    category: "team_blog",
    targetTeam: "CAR",
    targetTeamName: "Carolina Panthers",
    statusText: "済",
    isPermitted: true,
    showInTeamLatest: false,
    rssUrl: "https://note.com/pantherblue/rss",
    memo: "全てOK",
  },
  {
    id: 19,
    name: "Do Your Job - NFL Patriots Fan Blog -",
    url: "https://pats185.livedoor.blog/",
    category: "team_blog",
    targetTeam: "NE",
    targetTeamName: "New England Patriots",
    statusText: "済",
    isPermitted: true,
    showInTeamLatest: false,
    rssUrl: "https://pats185.livedoor.blog/index.rdf",
    memo: "全てOK",
  },
  {
    id: 20,
    name: "ちょび太のお気楽日記",
    url: "https://ameblo.jp/lovelycat-chobi/",
    category: "team_blog",
    targetTeam: "SEA",
    targetTeamName: "Seattle Seahawks",
    statusText: "済",
    isPermitted: true,
    showInTeamLatest: false,
    rssUrl: "https://rssblog.ameba.jp/lovelycat-chobi/rss20.xml",
    memo: "テーマにシーホークスがついているもの",
  },
  {
    id: 21,
    name: "くうた",
    url: "https://note.com/kuuta_browns",
    category: "team_blog",
    targetTeam: "CLE",
    targetTeamName: "Cleveland Browns",
    statusText: "リプライ済",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://note.com/kuuta_browns/rss",
    memo: "全てOK",
  },
  {
    id: 22,
    name: "NFL_SAMURAI",
    url: "https://note.com/juicy_coot952",
    category: "general",
    statusText: "リプライ済",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://note.com/juicy_coot952/rss",
    memo: "リンクのみ",
  },
  {
    id: 23,
    name: "WhoDeyJapan",
    url: "https://note.com/whodeyjapan",
    category: "team_blog",
    targetTeam: "CIN",
    targetTeamName: "Cincinnati Bengals",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://note.com/whodeyjapan/rss",
    memo: "全てOK",
  },
  {
    id: 24,
    name: "bufbillsのもやもやビルズ",
    url: "https://bufbills.exblog.jp/",
    category: "team_blog",
    targetTeam: "BUF",
    targetTeamName: "Buffalo Bills",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://bufbills.exblog.jp/index.xml",
    memo: "全てOK",
  },
  {
    id: 25,
    name: "isisi",
    url: "https://note.com/isisi",
    category: "team_blog",
    targetTeam: "PHI",
    targetTeamName: "Philadelphia Eagles",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://note.com/isisi/rss",
    memo: "全てOK",
  },
  {
    id: 26,
    name: "ディフェンド・ザ・ノース",
    url: "http://blog.livedoor.jp/kobasoo",
    category: "team_blog",
    targetTeam: "MIN",
    targetTeamName: "Minnesota Vikings",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "http://blog.livedoor.jp/kobasoo/index.rdf",
    memo: "全てOK",
  },
  {
    id: 27,
    name: "BEAR DOWN! Chicago Bears",
    url: "https://chicagobears.blog.jp/",
    category: "team_blog",
    targetTeam: "CHI",
    targetTeamName: "Chicago Bears",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://chicagobears.blog.jp/index.rdf",
    memo: "全てOK",
  },
  {
    id: 28,
    name: "broncomaniacのブログ版",
    url: "https://broncomaniac.blog.fc2.com/",
    category: "team_blog",
    targetTeam: "DEN",
    targetTeamName: "Denver Broncos",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://broncomaniac.blog.fc2.com/?xml",
    memo: "全てOK",
  },
  {
    id: 29,
    name: "Burgundy & Gold",
    url: "https://washingtonredskins.seesaa.net/",
    category: "team_blog",
    targetTeam: "WAS",
    targetTeamName: "Washington Commanders",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://washingtonredskins.seesaa.net/index.rdf",
    memo: "全てOK",
  },
  {
    id: 30,
    name: "NYGを応援してるかもしれないブログ",
    url: "https://nygmad.blog.jp/",
    category: "team_blog",
    targetTeam: "NYG",
    targetTeamName: "New York Giants",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://nygmad.blog.jp/index.rdf",
    memo: "全てOK",
  },
  {
    id: 31,
    name: "RAIDERSを愛する漢のブログ",
    url: "https://raidernationtokyo.blog.jp/",
    category: "team_blog",
    targetTeam: "LV",
    targetTeamName: "Las Vegas Raiders",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://raidernationtokyo.blog.jp/index.rdf",
    memo: "全てOK",
  },
  {
    id: 32,
    name: "TEXANS SWARM",
    url: "https://texans-swarm.hatenablog.jp/",
    category: "team_blog",
    targetTeam: "HOU",
    targetTeamName: "Houston Texans",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://texans-swarm.hatenablog.jp/rss",
    memo: "全てOK",
  },
  {
    id: 33,
    name: "TITANS SACK MANIA",
    url: "https://titanssackmania.blog.fc2.com/",
    category: "team_blog",
    targetTeam: "TEN",
    targetTeamName: "Tennessee Titans",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://titanssackmania.blog.fc2.com/?xml",
    memo: "全てOK",
  },
  {
    id: 34,
    name: "アリゾナマニアの知ったか発言集III",
    url: "https://arizona-mania.hatenablog.com/",
    category: "team_blog",
    targetTeam: "ARI",
    targetTeamName: "Arizona Cardinals",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://arizona-mania.hatenablog.com/rss",
    memo: "全てOK",
  },
  {
    id: 35,
    name: "コルツの国から",
    url: "http://blog.livedoor.jp/coltsjp",
    category: "team_blog",
    targetTeam: "IND",
    targetTeamName: "Indianapolis Colts",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "http://blog.livedoor.jp/coltsjp/index.rdf",
    memo: "全てOK",
  },
  {
    id: 36,
    name: "超個人的NFL備忘録",
    url: "http://blog.livedoor.jp/yasgt-nfl",
    category: "team_blog",
    targetTeam: "PIT",
    targetTeamName: "Pittsburgh Steelers",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "http://blog.livedoor.jp/yasgt-nfl/index.rdf",
    memo: "全てOK",
  },
  {
    id: 37,
    name: "鷲の巣",
    url: "https://eagles-nest.hatenablog.com/",
    category: "team_blog",
    targetTeam: "PHI",
    targetTeamName: "Philadelphia Eagles",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://eagles-nest.hatenablog.com/rss",
    memo: "全てOK",
  },
  {
    id: 38,
    name: "みとこが",
    url: "https://note.com/terakoya32",
    category: "team_blog",
    targetTeam: "SEA",
    targetTeamName: "Seattle Seahawks",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    filterRule: {
      targetUrlPattern: /m\/mf8c430a3d168/,
    },
    rssUrl: "https://note.com/terakoya32/rss",
    memo: "アメフト記事まとめ（https://note.com/terakoya32/m/mf8c430a3d168）のもののみ",
  },
  {
    id: 39,
    name: "NFL全試合観戦記",
    url: "https://woodheadmoss.com",
    category: "general",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    memo: "リンクのみ",
  },
  {
    id: 40,
    name: "beanbag",
    url: "https://note.com/faircatch",
    category: "general",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://note.com/faircatch/rss",
    memo: "リンクのみ",
  },
  {
    id: 41,
    name: "しゅうまい12ブログ",
    url: "https://shumai12sea.hatenablog.com/",
    category: "team_blog",
    targetTeam: "SEA",
    targetTeamName: "Seattle Seahawks",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    filterRule: {
      targetUrlPattern: /archive\/category\/Seahawks/,
    },
    rssUrl: "https://shumai12sea.hatenablog.com/rss",
    memo: "カテゴリー（https://shumai12sea.hatenablog.com/archive/category/Seahawks）のみチームページへ",
  },
  {
    id: 42,
    name: "アローヘッドな日々／チーフスブログ",
    url: "http://arrowheadlike.blog.fc2.com/",
    category: "team_blog",
    targetTeam: "KC",
    targetTeamName: "Kansas City Chiefs",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "http://arrowheadlike.blog.fc2.com/?xml",
    memo: "全てOK",
  },
  {
    id: 43,
    name: "ジャガーズ中毒",
    url: "https://gooooya.livedoor.blog/",
    category: "team_blog",
    targetTeam: "JAX",
    targetTeamName: "Jacksonville Jaguars",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://gooooya.livedoor.blog/index.rdf",
    memo: "全てOK",
  },
  {
    id: 44,
    name: "ダラスカウボーイズファン",
    url: "https://note.com/cowboysjapan",
    category: "team_blog",
    targetTeam: "DAL",
    targetTeamName: "Dallas Cowboys",
    statusText: "連絡手段なし",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://note.com/cowboysjapan/rss",
    memo: "仕訳必要",
  },
  {
    id: 45,
    name: "AmesNFL",
    url: "https://ames-nfl.com/",
    category: "special",
    statusText: "神サイト",
    isPermitted: true, // 最上位固定のため常に最優先
    isPinnedTop: true,
    showInTeamLatest: false,
    rssUrl: "https://ames-nfl.com/rss",
    memo: "リンクのみ",
  },
  {
    id: 46,
    name: "DB アイランド−NFL ARI フラッグ−",
    url: "https://nfl-cardinals.com/",
    category: "general",
    statusText: "届いていない？",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://nfl-cardinals.com/feed/",
    memo: "リンクのみ",
  },
  {
    id: 47,
    name: "FTTB's Playbook ｜ Bang Bang!",
    url: "https://note.com/fttb49ers",
    category: "general",
    statusText: "未設定",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://note.com/fttb49ers/rss",
    memo: "リンクのみ",
  },
  {
    id: 48,
    name: "hiro",
    url: "https://note.com/kind_quokka9252",
    category: "general",
    statusText: "未設定",
    isPermitted: false,
    showInTeamLatest: false,
    rssUrl: "https://note.com/kind_quokka9252/rss",
    memo: "リンクのみ",
  },
];

/**
 * リンク集ページ向けのソート済みリストを取得
 * 1. No.45 Ames を最上位（Pinned）
 * 2. 許諾済み（isPermitted = true）を昇順
 * 3. 未許諾・連絡待ちをID順
 */
export function getSortedMediaLinks(): NFLMediaLinkItem[] {
  return [...NFL_MEDIA_LINKS].sort((a, b) => {
    if (a.isPinnedTop) return -1;
    if (b.isPinnedTop) return 1;
    if (a.isPermitted && !b.isPermitted) return -1;
    if (!a.isPermitted && b.isPermitted) return 1;
    return a.id - b.id;
  });
}
