CREATE TABLE `advanced_supplement_imports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`season` int NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`rowsApplied` int NOT NULL DEFAULT 0,
	`uploadedBy` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `advanced_supplement_imports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `season_imports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`season` int NOT NULL,
	`status` enum('ready','importing','failed') NOT NULL DEFAULT 'ready',
	`sourceUrl` text,
	`gamesImported` int NOT NULL DEFAULT 0,
	`rowsImported` int NOT NULL DEFAULT 0,
	`importedBy` varchar(64),
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastReadyAt` timestamp,
	CONSTRAINT `season_imports_id` PRIMARY KEY(`id`),
	CONSTRAINT `season_imports_season_unique` UNIQUE(`season`)
);
--> statement-breakpoint
CREATE TABLE `season_refresh_schedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`season` int NOT NULL,
	`name` varchar(100) NOT NULL,
	`cronExpression` varchar(64) NOT NULL,
	`scheduleCronTaskUid` varchar(65),
	`isEnabled` boolean NOT NULL DEFAULT false,
	`lastStatus` enum('pending_deploy','ready','running','waiting_for_source','failed') NOT NULL DEFAULT 'pending_deploy',
	`lastRunAt` timestamp,
	`lastSuccessAt` timestamp,
	`lastError` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `season_refresh_schedules_id` PRIMARY KEY(`id`),
	CONSTRAINT `season_refresh_schedules_season_unique` UNIQUE(`season`),
	CONSTRAINT `season_refresh_schedules_task_uid_unique` UNIQUE(`scheduleCronTaskUid`)
);
--> statement-breakpoint
CREATE TABLE `team_week_matchups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`season` int NOT NULL,
	`team` varchar(3) NOT NULL,
	`week` tinyint NOT NULL,
	`opponent` varchar(3) NOT NULL,
	`isHome` boolean NOT NULL,
	`gameId` varchar(32) NOT NULL,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `team_week_matchups_id` PRIMARY KEY(`id`),
	CONSTRAINT `team_week_matchups_season_team_week_unique` UNIQUE(`season`,`team`,`week`)
);
--> statement-breakpoint
CREATE TABLE `team_week_stats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`season` int NOT NULL,
	`team` varchar(3) NOT NULL,
	`week` tinyint NOT NULL,
	`games` int NOT NULL DEFAULT 0,
	`pointsFor` double NOT NULL DEFAULT 0,
	`pointsAgainst` double NOT NULL DEFAULT 0,
	`yardsFor` double NOT NULL DEFAULT 0,
	`yardsAgainst` double NOT NULL DEFAULT 0,
	`passYardsFor` double NOT NULL DEFAULT 0,
	`rushYardsFor` double NOT NULL DEFAULT 0,
	`passYardsAgainst` double NOT NULL DEFAULT 0,
	`rushYardsAgainst` double NOT NULL DEFAULT 0,
	`offenseEpa` double NOT NULL DEFAULT 0,
	`offenseEpaPlays` int NOT NULL DEFAULT 0,
	`defenseEpaAllowed` double NOT NULL DEFAULT 0,
	`defenseEpaPlays` int NOT NULL DEFAULT 0,
	`passAttempts` int NOT NULL DEFAULT 0,
	`passCompletions` int NOT NULL DEFAULT 0,
	`passTouchdowns` int NOT NULL DEFAULT 0,
	`interceptionsThrown` int NOT NULL DEFAULT 0,
	`sacksAllowed` int NOT NULL DEFAULT 0,
	`sacksDefense` int NOT NULL DEFAULT 0,
	`interceptionsDefense` int NOT NULL DEFAULT 0,
	`turnovers` int NOT NULL DEFAULT 0,
	`thirdDownAttempts` int NOT NULL DEFAULT 0,
	`thirdDownConversions` int NOT NULL DEFAULT 0,
	`opponentThirdDownAttempts` int NOT NULL DEFAULT 0,
	`opponentThirdDownConversions` int NOT NULL DEFAULT 0,
	`redZoneAttempts` int NOT NULL DEFAULT 0,
	`redZoneTouchdowns` int NOT NULL DEFAULT 0,
	`opponentRedZoneAttempts` int NOT NULL DEFAULT 0,
	`opponentRedZoneTouchdowns` int NOT NULL DEFAULT 0,
	`fieldGoalAttempts` int NOT NULL DEFAULT 0,
	`fieldGoalsMade` int NOT NULL DEFAULT 0,
	`extraPointAttempts` int NOT NULL DEFAULT 0,
	`extraPointsMade` int NOT NULL DEFAULT 0,
	`puntAttempts` int NOT NULL DEFAULT 0,
	`puntsInside20` int NOT NULL DEFAULT 0,
	`penalties` int NOT NULL DEFAULT 0,
	`penaltyYards` int NOT NULL DEFAULT 0,
	`blitzPct` double,
	`missedTackles` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `team_week_stats_id` PRIMARY KEY(`id`),
	CONSTRAINT `team_week_stats_season_team_week_unique` UNIQUE(`season`,`team`,`week`)
);
