import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { AlertCircle, CalendarClock, Database, Loader2, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

function Workspace() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const { data: imports = [] } = trpc.fieldlineAdmin.imports.useQuery(); const { data: schedules = [] } = trpc.fieldlineAdmin.refreshSchedules.useQuery(); const [season, setSeason] = useState("2025"); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const importSeason = trpc.fieldlineAdmin.importSeason.useMutation({ onSuccess: result => { setNotice(`${result.season}年を更新しました。${result.gamesImported}試合、${result.rowsImported.toLocaleString()}プレーを保存しました。`); utils.fieldlineAdmin.imports.invalidate(); utils.fieldline.seasons.invalidate(); utils.fieldline.freshness.invalidate(); }, onError: failure => setError(failure.message) });
  if (user?.role !== "admin") return <div className="mx-auto max-w-2xl py-16 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-slate-300" /><h1 className="mt-4 text-xl font-semibold">管理者専用ページです</h1><p className="mt-2 text-sm text-slate-500">データ更新の管理は、プロジェクト管理者のみ実行できます。</p><Link href="/fieldline/" className="mt-5 inline-block text-sm font-medium text-[#9a7530]">比較画面へ戻る</Link></div>;
  return <div className="mx-auto max-w-5xl space-y-7 py-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold tracking-[0.16em] text-[#9a7530]">FIELDLINE ADMIN WORKSPACE</p><h1 className="mt-1 font-serif text-3xl text-[#162038]">データ運用</h1><p className="mt-2 text-sm text-slate-500">nflverseのシーズンデータ取込と自動更新の稼働状況を管理します。</p></div><Link href="/fieldline/" className="text-sm font-medium text-slate-500 hover:text-[#162038]">比較画面へ戻る</Link></div>
    {notice && <Alert className="border-emerald-200 bg-emerald-50 text-emerald-900"><AlertTitle>処理が完了しました</AlertTitle><AlertDescription>{notice}</AlertDescription></Alert>}{error && <Alert variant="destructive"><AlertCircle className="h-4 w-4" /><AlertTitle>処理できませんでした</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="h-5 w-5 text-[#9a7530]" />シーズンデータ更新</CardTitle><CardDescription>nflverseのParquetファイルをサーバー側で読み込み、Week 1〜18の集計を保存します。</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="fieldline-season">対象シーズン</Label><Input id="fieldline-season" type="number" min="2025" value={season} onChange={event => setSeason(event.target.value)} /></div><Button className="w-full bg-[#162038] hover:bg-[#243252]" disabled={importSeason.isPending} onClick={() => { setError(null); setNotice(null); importSeason.mutate({ season: Number(season) }); }}>{importSeason.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{importSeason.isPending ? "集計・保存中…" : "nflverseから更新"}</Button><p className="text-xs leading-5 text-slate-400">処理には数分かかることがあります。別の更新操作は、完了後に実行してください。</p></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-[#9a7530]" />自動更新スケジュール</CardTitle><CardDescription>公開後は毎週水曜日 06:00 JST（火曜日 21:00 UTC）にnflverseの更新を確認します。</CardDescription></CardHeader><CardContent className="space-y-3">{schedules.length ? schedules.map(schedule => <div key={schedule.season} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><div className="flex items-center justify-between"><p className="font-semibold text-slate-800">{schedule.season} Season</p><span className={`rounded-full px-2 py-1 text-xs font-medium ${schedule.lastStatus === "ready" ? "bg-emerald-50 text-emerald-700" : schedule.lastStatus === "failed" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}>{schedule.lastStatus}</span></div><p className="mt-1 text-xs text-slate-500">{schedule.scheduleCronTaskUid ? "Heartbeatが有効です。" : "公開後にHeartbeatを有効化します。"}</p></div>) : <p className="text-sm text-slate-500">自動更新の設定を読み込んでいます。</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>取込履歴</CardTitle><CardDescription>比較画面に利用できるシーズンと最後の処理状況です。</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3">Season</th><th className="pb-3">Status</th><th className="pb-3">Games</th><th className="pb-3">Plays</th><th className="pb-3">Updated</th></tr></thead><tbody>{imports.length ? imports.map(item => <tr key={item.season} className="border-b border-slate-100 last:border-0"><td className="py-3 font-semibold">{item.season}</td><td className="py-3"><span className={`rounded-full px-2 py-1 text-xs font-medium ${item.status === "ready" ? "bg-emerald-50 text-emerald-700" : item.status === "failed" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}>{item.status}</span></td><td className="py-3 text-slate-600">{item.gamesImported}</td><td className="py-3 text-slate-600">{item.rowsImported.toLocaleString()}</td><td className="py-3 text-slate-500">{new Date(item.updatedAt).toLocaleString()}</td></tr>) : <tr><td colSpan={5} className="py-8 text-center text-slate-500">取込履歴はまだありません。</td></tr>}</tbody></table></div></CardContent></Card>
  </div>;
}

export default function FieldlineAdmin() { return <DashboardLayout><Workspace /></DashboardLayout>; }
