import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const appSource = readFileSync(resolve(process.cwd(), "client/src/App.tsx"), "utf8");
const homeSource = readFileSync(resolve(process.cwd(), "client/src/pages/Home.tsx"), "utf8");
const atlasSource = readFileSync(resolve(process.cwd(), "client/src/pages/Atlas.tsx"), "utf8");
const fieldlineSource = readFileSync(resolve(process.cwd(), "client/src/pages/Fieldline.tsx"), "utf8");
const fieldlineAdminSource = readFileSync(resolve(process.cwd(), "client/src/pages/FieldlineAdmin.tsx"), "utf8");
const fieldlineDataSource = readFileSync(resolve(process.cwd(), "server/fieldlineData.ts"), "utf8");
const embeddedNavSource = readFileSync(resolve(process.cwd(), "client/src/components/EmbeddedAppNav.tsx"), "utf8");
const indexHtml = readFileSync(resolve(process.cwd(), "client/index.html"), "utf8");

describe("ATLAS and FIELDLINE integration routes", () => {
  it("registers native ATLAS and FIELDLINE routes without restoring either external redirect flow", () => {
    expect(appSource).toContain('path="/atlas"');
    expect(appSource).toContain('path="/fieldline"');
    expect(appSource).toContain('const Atlas = lazy(preloadAtlasRoute)');
    expect(appSource).toContain('const Fieldline = lazy(preloadFieldlineRoute)');
    expect(appSource).toContain("<Suspense fallback={<RouteLoading />}>");
    expect(homeSource).toContain('ATLAS');
    expect(homeSource).toContain('FIELDLINE');
    expect(homeSource).toContain('onPointerEnter={warmAtlasRoute}');
    expect(homeSource).toContain('onPointerEnter={warmFieldlineRoute}');
    expect(homeSource).toContain('onPointerDown={warmAtlasRoute}');
    expect(homeSource).toContain('onPointerDown={warmFieldlineRoute}');
    expect(atlasSource).toContain('atlas-shell');
    expect(atlasSource).toContain('atlas-display');
    expect(fieldlineSource).toContain('EmbeddedAppNav current="FIELDLINE"');
    expect(atlasSource).toContain('trpc.atlas.search.useQuery');
    expect(atlasSource).toContain('trpc.atlas.profile.useQuery');
    expect(atlasSource).toContain('trpc.atlas.career.useQuery');
    expect(atlasSource).toContain('trpc.atlas.awards.useQuery');
    expect(atlasSource).toContain('trpc.atlas.stats.useQuery');
    expect(atlasSource).toContain('trpc.atlas.contracts.useQuery');
    expect(atlasSource).toContain('キャリア');
    expect(atlasSource).toContain('契約情報');
    expect(atlasSource).toContain('現契約の年度別内訳');
    expect(atlasSource).toContain('SIGN / PRORATED');
    expect(atlasSource).toContain('VOID');
    expect(atlasSource).toContain('ワークアウト、試合別ロスター、その他ボーナス');
    expect(atlasSource).toContain('契約履歴');
    expect(atlasSource).toContain('EARNED');
    expect(atlasSource).toContain('enabled: mode === "filter"');
    expect(atlasSource).toContain('NFL PLAYER');
    expect(atlasSource).not.toContain('window.location.replace');
    expect(atlasSource).not.toContain('nflplayeratl-tus9mrqw.manus.space');
    expect(fieldlineSource).toContain('trpc.fieldline.compare.useQuery');
    expect(fieldlineSource).toContain('trpc.fieldline.weeks.useQuery');
    expect(fieldlineSource).toContain('LEFT COMPARISON');
    expect(fieldlineSource).toContain('RIGHT COMPARISON');
    expect(fieldlineSource).toContain('OFFENSE');
    expect(fieldlineSource).toContain('SPECIAL TEAMS');
    expect(fieldlineSource).toContain('EmbeddedAppNav current="FIELDLINE"');
    expect(fieldlineDataSource).toContain('importFieldlineSeasonFromNflverse');
    expect(fieldlineDataSource).toContain('compareFieldlineSelections');
    expect(fieldlineDataSource).toContain('fieldlinePbpSource');
    expect(fieldlineAdminSource).toContain('trpc.fieldlineAdmin.importSeason');
    expect(appSource).toContain('path="/fieldline/admin"');
    expect(atlasSource).not.toContain('<iframe');
    expect(fieldlineSource).not.toContain('<iframe');
    expect(indexHtml).not.toContain('nflplayeratl-tus9mrqw.manus.space');
    expect(indexHtml).not.toContain('nflteamstats-4q87cnse.manus.space');
    expect(fieldlineSource).not.toContain('nflteamstats-4q87cnse.manus.space');
    expect(fieldlineSource).not.toContain('window.location.replace');
    expect(fieldlineSource).toContain('container mx-auto max-w-6xl px-4 pt-1 pb-6 sm:px-6 sm:pt-2 sm:pb-8');
    expect(embeddedNavSource).toContain('Menu');
    expect(embeddedNavSource).toContain('HOME');
    expect(embeddedNavSource).toContain('ATLAS');
    expect(embeddedNavSource).toContain('FIELDLINE');
    expect(atlasSource).toContain('atlasUtils.atlas.contracts.prefetch');
    expect(atlasSource).toContain('atlasUtils.atlas.stats.prefetch');
    expect(atlasSource).toContain('const warmDetailTab');
    expect(atlasSource).toContain('onPointerEnter={() => warmDetailTab(tab)}');
    expect(atlasSource).toContain('}, 360)');
    expect(atlasSource).toContain('staleTime: 12 * 60 * 60_000');
    expect(atlasSource).toContain('staleTime: 24 * 60 * 60_000');
  });
});
