import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const appSource = readFileSync(resolve(process.cwd(), "client/src/App.tsx"), "utf8");
const homeSource = readFileSync(resolve(process.cwd(), "client/src/pages/Home.tsx"), "utf8");
const atlasSource = readFileSync(resolve(process.cwd(), "client/src/pages/Atlas.tsx"), "utf8");
const coachingTreeSource = readFileSync(resolve(process.cwd(), "client/src/pages/CoachingTree.tsx"), "utf8");
const coachingTreeDataSource = readFileSync(resolve(process.cwd(), "client/src/data/centralAtlas.ts"), "utf8");
const coachingTreeRepairSource = readFileSync(resolve(process.cwd(), "client/src/components/coachingTreeRepair.css"), "utf8");
const coachingTreeMobileClaritySource = readFileSync(resolve(process.cwd(), "client/src/components/coachingTreeMobileClarity.css"), "utf8");
const fieldlineSource = readFileSync(resolve(process.cwd(), "client/src/pages/Fieldline.tsx"), "utf8");
const fieldlineAdminSource = readFileSync(resolve(process.cwd(), "client/src/pages/FieldlineAdmin.tsx"), "utf8");
const fieldlineDataSource = readFileSync(resolve(process.cwd(), "server/fieldlineData.ts"), "utf8");
const embeddedNavSource = readFileSync(resolve(process.cwd(), "client/src/components/EmbeddedAppNav.tsx"), "utf8");
const indexHtml = readFileSync(resolve(process.cwd(), "client/index.html"), "utf8");

describe("embedded FAN/HUB application routes", () => {
  it("registers native ATLAS, COACHING TREE, and FIELDLINE routes without restoring external redirect flows", () => {
    expect(appSource).toContain('path="/atlas"');
    expect(appSource).toContain('path="/fieldline"');
    expect(appSource).toContain('const Atlas = lazy(preloadAtlasRoute)');
    expect(appSource).toContain('const CoachingTree = lazy(preloadCoachingTreeRoute)');
    expect(appSource).toContain('const Fieldline = lazy(preloadFieldlineRoute)');
    expect(appSource).toContain("<Suspense fallback={<RouteLoading />}>");
    expect(homeSource).toContain('ATLAS');
    expect(homeSource).toContain('FIELDLINE');
    expect(homeSource).toContain('COACHING TREE');
    expect(homeSource).toContain('onPointerEnter={warmAtlasRoute}');
    expect(homeSource).toContain('onPointerEnter={warmCoachingTreeRoute}');
    expect(homeSource).toContain('onPointerEnter={warmFieldlineRoute}');
    expect(homeSource).toContain('onPointerDown={warmAtlasRoute}');
    expect(homeSource).toContain('onPointerDown={warmFieldlineRoute}');
    expect(atlasSource).toContain('atlas-shell');
    expect(atlasSource).toContain('atlas-display');
    expect(fieldlineSource).toContain('EmbeddedAppNav current="FIELDLINE"');
    expect(atlasSource).toContain('trpc.atlas.search.useQuery');
    expect(atlasSource).toContain('trpc.atlas.profile.useQuery');
    expect(atlasSource).toContain('trpc.atlas.career.useQuery');
    expect(atlasSource).toContain('trpc.atlas.awards.useQuery');
    expect(atlasSource).toContain('trpc.atlas.stats.useQuery');
    expect(atlasSource).toContain('trpc.atlas.contracts.useQuery');
    expect(atlasSource).toContain('キャリア');
    expect(atlasSource).toContain('契約情報');
    expect(atlasSource).toContain('現契約の年度別内訳');
    expect(atlasSource).toContain('SIGN / PRORATED');
    expect(atlasSource).toContain('VOID');
    expect(atlasSource).toContain('ワークアウト、試合別ロスター、その他ボーナス');
    expect(atlasSource).toContain('契約履歴');
    expect(atlasSource).toContain('EARNED');
    expect(atlasSource).toContain('enabled: mode === "filter"');
    expect(atlasSource).toContain('NFL PLAYER');
    expect(atlasSource).not.toContain('window.location.replace');
    expect(atlasSource).not.toContain('nflplayeratl-tus9mrqw.manus.space');
    expect(fieldlineSource).toContain('trpc.fieldline.compare.useQuery');
    expect(fieldlineSource).toContain('trpc.fieldline.weeks.useQuery');
    expect(fieldlineSource).toContain('LEFT COMPARISON');
    expect(fieldlineSource).toContain('RIGHT COMPARISON');
    expect(fieldlineSource).toContain('OFFENSE');
    expect(fieldlineSource).toContain('SPECIAL TEAMS');
    expect(fieldlineSource).toContain('EmbeddedAppNav current="FIELDLINE"');
    expect(fieldlineDataSource).toContain('importFieldlineSeasonFromNflverse');
    expect(fieldlineDataSource).toContain('compareFieldlineSelections');
    expect(fieldlineDataSource).toContain('fieldlinePbpSource');
    expect(fieldlineAdminSource).toContain('trpc.fieldlineAdmin.importSeason');
    expect(appSource).toContain('path="/fieldline/admin"');
    expect(appSource).toContain('path="/coaching-tree"');
    expect(coachingTreeSource).toContain('EmbeddedAppNav current="COACHING TREE"');
    expect(coachingTreeSource).toContain('CROSS-TREE PATHFINDER');
    expect(coachingTreeSource).toContain('HC在任期間のスタッフ年鑑');
    expect(coachingTreeSource).toContain('RelationEvidence');
    expect(coachingTreeSource).toContain('const matchingAlmanacCoach');
    expect(coachingTreeSource).toContain('setStaffCoachId(matchingAlmanacCoach.id)');
    expect(coachingTreeSource).toContain('selectTree(containingTree.id, nextId)');
    expect(coachingTreeSource).toContain('function selectTree(treeId: string, selectedCoachId?: string)');
    expect(coachingTreeSource).toContain('getFittedMapZoom');
    expect(coachingTreeSource).toContain('profile-role-glyph');
    expect(coachingTreeRepairSource).toContain('.atlas-app .atlas-shell');
    expect(coachingTreeRepairSource).toContain('transform-origin: left top');
    expect(coachingTreeRepairSource).toContain('height: min(68vh, 700px)');
    expect(coachingTreeSource).toContain('const [profileMapFocusId, setProfileMapFocusId]');
    expect(coachingTreeSource).toContain('setProfileMapFocusId(selectedId)');
    expect(coachingTreeSource).toContain('lineageDepthByTreeId');
    expect(coachingTreeSource).toContain('data-lineage-depth={location.depth}');
    expect(coachingTreeMobileClaritySource).toContain('.tree-switches button.is-active');
    expect(coachingTreeMobileClaritySource).toContain('.coach-dot.is-profile-focus');
    expect(coachingTreeMobileClaritySource).toContain('grid-template-columns: 96px minmax(0, 1fr)');
    expect(coachingTreeMobileClaritySource).toContain('min-height: 38px');
    expect(coachingTreeDataSource).toContain('centralAtlasTrees');
    expect(atlasSource).not.toContain('<iframe');
    expect(fieldlineSource).not.toContain('<iframe');
    expect(indexHtml).not.toContain('nflplayeratl-tus9mrqw.manus.space');
    expect(indexHtml).not.toContain('nflteamstats-4q87cnse.manus.space');
    expect(fieldlineSource).not.toContain('nflteamstats-4q87cnse.manus.space');
    expect(fieldlineSource).not.toContain('window.location.replace');
    expect(fieldlineSource).toContain('container mx-auto max-w-6xl px-4 pt-1 pb-6 sm:px-6 sm:pt-2 sm:pb-8');
    expect(embeddedNavSource).toContain('Menu');
    expect(embeddedNavSource).toContain('HOME');
    expect(embeddedNavSource).toContain('ATLAS');
    expect(embeddedNavSource).toContain('COACHING TREE');
    expect(embeddedNavSource).toContain('FIELDLINE');
    expect(atlasSource).toContain('atlasUtils.atlas.contracts.prefetch');
    expect(atlasSource).toContain('atlasUtils.atlas.stats.prefetch');
    expect(atlasSource).toContain('const warmDetailTab');
    expect(atlasSource).toContain('onPointerEnter={() => warmDetailTab(tab)}');
    expect(atlasSource).toContain('}, 360)');
    expect(atlasSource).toContain('staleTime: 12 * 60 * 60_000');
    expect(atlasSource).toContain('staleTime: 24 * 60 * 60_000');
  });
});
